MODULE CREATE_TOP
   USE PREC_HIRE
   USE CG_DATA
   USE TOP_GLOBALS
   CHARACTER(LEN=40) :: TOPNAME="parameters.top"
   CONTAINS

      SUBROUTINE WRITE_TOPOLOGY()
         USE UTILS_IO, ONLY: GETUNIT
         IMPLICIT NONE
         INTEGER :: TOPUNIT

         TOPUNIT = GETUNIT()
         OPEN(UNIT=TOPUNIT, FILE=TOPNAME, STATUS='NEW')

         CALL WRITE_PARTICLE_RES_INFO(TOPUNIT)

         CLOSE(TOPUNIT)
      END SUBROUTINE WRITE_TOPOLOGY


      SUBROUTINE WRITE_PARTICLE_RES_INFO(TOPUNIT)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: TOPUNIT
         INTEGER :: I
         !particle names
         WRITE(TOPUNIT,*) "SECTION PARTICLE_NAMES"
         WRITE(TOPUNIT,'(20A4)') CGNAMES
         !residue names
         WRITE(TOPUNIT,*) "SECTION RESIDUE_NAMES"
         WRITE(TOPUNIT,'(20A4)') CGRESNAMES
         !residue start and finish indices
         WRITE(TOPUNIT,*) "SECTION RESIDUE_POINTER"   
         WRITE(TOPUNIT,'(12I6)') (CGSTART(I),CGFINAL(I), I=1,NRES)
         !termini
         WRITE(TOPUNIT,*) "SECTION CHAIN_POINTER"
         WRITE(TOPUNIT,'(12I6)') TERMINI
      END SUBROUTINE WRITE_PARTICLE_RES_INFO

END MODULE CREATE_TOP