MODULE PARSE_CG_PDB
   USE PARSE_PDB
   USE TOP_GLOBALS
   USE PREC_HIRE, ONLY: REAL64
   IMPLICIT NONE

   CONTAINS
      SUBROUTINE PARSE_CG_INPUT(INPUTNAME)
         USE CG_DATA, ONLY: ASSIGN_GRAIN_DATA, GET_RES_DATA
         CHARACTER(LEN=256), INTENT(IN) :: INPUTNAME
         LOGICAL :: DEBUGT = .FALSE.
         INTEGER :: I

         CALL PARSE_PDB_FILE(INPUTNAME)

         CALL GET_RES_DATA(PDBRESNAMES)
         CALL ASSIGN_GRAIN_DATA()
         XYZCG = XYZPDB !CG data is already present in the CG PDB file

         IF (DEBUGT) THEN
            DO I=1,NATOMS
               WRITE(*,'(A,3F12.7)') CGNAMES(I), XYZCG(3*I-2:3*I)
            END DO
         END IF
      END SUBROUTINE PARSE_CG_INPUT

END MODULE PARSE_CG_PDB
