MODULE PARSE_AA_PDB
   USE PARSE_PDB
   USE TOP_GLOBALS
   USE PREC_HIRE, ONLY: REAL64
   IMPLICIT NONE

   CONTAINS
      SUBROUTINE PARSE_AA_INPUT(INPUTNAME)
         USE CG_DATA, ONLY: ASSIGN_GRAIN_DATA, GET_RES_DATA
         CHARACTER(LEN=256), INTENT(IN) :: INPUTNAME
         LOGICAL :: DEBUGT = .FALSE.
         INTEGER :: I

         CALL PARSE_PDB_FILE(INPUTNAME)

         CALL GET_RES_DATA(PDBRESNAMES)
         CALL ASSIGN_GRAIN_DATA()
         CALL CREATE_CG_XYZ() !at this point we have all the data, now create the CG data from it

         IF (DEBUGT) THEN
            DO I=1,NATOMS
               WRITE(*,'(A,3F12.7)') CGNAMES(I), XYZCG(3*I-2:3*I)
            END DO
         END IF
      END SUBROUTINE PARSE_AA_INPUT

      SUBROUTINE CREATE_CG_XYZ()
         IMPLICIT NONE
         INTEGER :: I, J
         INTEGER :: ATOMIDAA, ATOMIDCG

         DO I=1,NRES
            IF (RESTYPE(I).EQ.2) THEN !ions only have one set of coordinates
               ATOMIDAA = AARESSTART(J)
               ATOMIDCG = CGSTART(J)
               CALL ASSIGN_AA_TO_CG(ATOMIDAA,ATOMIDCG)
            ELSE IF ((RESTYPE(I).EQ.0).OR.(RESTYPE(I).EQ.1)) THEN !RNA and DNA
               DO J=CGSTART(I),CGFINAL(I)
                  IF (CGNAMES(J).EQ."P") THEN
                     CALL GET_ATOMID("P",I,ATOMIDAA)
                     CALL ASSIGN_AA_TO_CG(ATOMIDAA,J)
                  ELSE IF (CGNAMES(J).EQ."O5") THEN
                     CALL GET_ATOMID("O5'",I,ATOMIDAA)
                     CALL ASSIGN_AA_TO_CG(ATOMIDAA,J)
                  ELSE IF (CGNAMES(J).EQ."O3") THEN
                     CALL GET_ATOMID("O3'",I,ATOMIDAA)
                     CALL ASSIGN_AA_TO_CG(ATOMIDAA,J)
                  ELSE IF ((CGNAMES(J).EQ."R4").OR.(CGNAMES(J).EQ."S4")) THEN
                     CALL GET_ATOMID("C4'",I,ATOMIDAA)
                     CALL ASSIGN_AA_TO_CG(ATOMIDAA,J)
                  ELSE IF ((CGNAMES(J).EQ."R1").OR.(CGNAMES(J).EQ."S1")) THEN
                     CALL GET_ATOMID("C1'",I,ATOMIDAA)
                     CALL ASSIGN_AA_TO_CG(ATOMIDAA,J)
                  ELSE
                     CALL GET_BASE_COORDS(I,J)
                  END IF
               END DO
            END IF
         END DO
      END SUBROUTINE CREATE_CG_XYZ

      SUBROUTINE GET_BASE_COORDS(RESID,CGID)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: RESID,CGID
         CHARACTER(LEN=4), ALLOCATABLE :: GRAINATOMS(:)
         INTEGER :: NATSINGRAIN
         REAL(KIND = REAL64) :: GRAINPOS(3)

         IF (CGNAMES(CGID).EQ."A1") THEN
            NATSINGRAIN = 5
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["C4","C5","N7","C8","N9"]
         ELSE IF (CGNAMES(CGID).EQ."A2") THEN
            NATSINGRAIN = 7
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["N1","C2","N3","C4","C5","C6","N6"]
         ELSE IF (CGNAMES(CGID).EQ."C1") THEN
            NATSINGRAIN = 8
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["N1","C2","O2","N3","N4","C4","C5","C6"]
         ELSE IF (CGNAMES(CGID).EQ."G1") THEN
            NATSINGRAIN = 5
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["C4","C5","N7","C8","N9"]
         ELSE IF (CGNAMES(CGID).EQ."G2") THEN
            NATSINGRAIN = 8
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["N1","C2","N2","N3","C4","C5","C6","O6"]
         ELSE IF (CGNAMES(CGID).EQ."T1") THEN
            NATSINGRAIN = 8
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["N1","C2","N3","C4","C5","C6","O2","O4"]
         ELSE IF (CGNAMES(CGID).EQ."U1") THEN
            NATSINGRAIN = 8
            ALLOCATE(GRAINATOMS(NATSINGRAIN))
            GRAINATOMS = ["N1","C2","N3","C4","C5","C6","O2","O4"]
         END IF
         CALL COMPUTE_GRAINPOS(NATSINGRAIN,GRAINATOMS,RESID,GRAINPOS)
         DEALLOCATE(GRAINATOMS)
         XYZCG(3*(CGID-1)+1:3*(CGID-1)+3) = GRAINPOS(1:3)
      END SUBROUTINE GET_BASE_COORDS

      SUBROUTINE COMPUTE_GRAINPOS(NATSINGRAIN,GRAINATOMS,RESID,GRAINPOS)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: NATSINGRAIN
         CHARACTER(LEN=4), INTENT(IN) :: GRAINATOMS(NATSINGRAIN)
         INTEGER, INTENT(IN) :: RESID
         REAL(KIND = REAL64), INTENT(OUT) :: GRAINPOS(3)

         INTEGER :: I, ATOMID
         REAL(KIND=REAL64) :: TOTALMASS, ATOMMASS

         GRAINPOS(1:3) = 0.0D0
         TOTALMASS = 0.0D0
         DO I=1,NATSINGRAIN
            CALL GET_ATOMID(GRAINATOMS(I),RESID,ATOMID)
            ATOMMASS = 0.0D0
            IF (INDEX(GRAINATOMS(I),"C").GT.0) THEN
               ATOMMASS = 12.011D0
            ELSE IF (INDEX(GRAINATOMS(I),"N").GT.0) THEN
               ATOMMASS = 14.007D0
            ELSE IF (INDEX(GRAINATOMS(I),"O").GT.0) THEN
               ATOMMASS = 15.999D0
            END IF
            TOTALMASS = TOTALMASS + ATOMMASS
            GRAINPOS(1) = GRAINPOS(1) + XYZPDB(3*(ATOMID-1)+1) * ATOMMASS
            GRAINPOS(2) = GRAINPOS(2) + XYZPDB(3*(ATOMID-1)+2) * ATOMMASS
            GRAINPOS(3) = GRAINPOS(3) + XYZPDB(3*(ATOMID-1)+3) * ATOMMASS
         END DO
         GRAINPOS(1:3) = GRAINPOS(1:3)/TOTALMASS
      END SUBROUTINE COMPUTE_GRAINPOS

      SUBROUTINE ASSIGN_AA_TO_CG(AAID,CGID)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: AAID, CGID
         XYZCG(3*(CGID-1)+1) = XYZPDB(3*(AAID-1)+1)
         XYZCG(3*(CGID-1)+2) = XYZPDB(3*(AAID-1)+2)
         XYZCG(3*(CGID-1)+3) = XYZPDB(3*(AAID-1)+3)
      END SUBROUTINE ASSIGN_AA_TO_CG

      !get atom id from name for given residue
      !returns 0 if atom does not exist in residue
      SUBROUTINE GET_ATOMID(ATNAME,RESID,ATOMID)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: RESID
         CHARACTER(*), INTENT(IN) :: ATNAME
         INTEGER, INTENT(OUT) :: ATOMID
         INTEGER :: FIRST, LAST, J1
         ATOMID = 0
         FIRST=AARESSTART(RESID)
         LAST=PDBRESFINAL(RESID)
         DO J1=FIRST,LAST
            IF (ADJUSTL(TRIM(PDBNAMES(J1))).EQ.ADJUSTL(TRIM(ATNAME))) THEN
               ATOMID = J1
               EXIT
            ENDIF
         ENDDO
         RETURN
      END SUBROUTINE GET_ATOMID

END MODULE PARSE_AA_PDB
