MODULE FF_GLOBALS
   USE PREC_HIRE
   !custom type to store bond information
   TYPE :: BOND
      CHARACTER(LEN=4) :: AT1, AT2
      REAL(KIND=REAL64) :: KSPR, REQ
   END TYPE
   !custom type to store angle information
   TYPE :: ANGLE
      CHARACTER(LEN=4) :: AT1, AT2, AT3
      REAL(KIND=REAL64) :: KSPR, TEQ
   END TYPE
   !custom type to store qangle information
   TYPE :: QANGLE
      CHARACTER(LEN=4) :: AT1, AT2, AT3
      REAL(KIND=REAL64) :: TTA, A1, A2, A3, A5
   END TYPE
   !custom dihedral information type
   TYPE :: DIHEDRAL
      CHARACTER(LEN=4) :: AT1, AT2, AT3, AT4
      REAL(KIND=REAL64) :: K, PHASE, YOFF
      INTEGER :: PERIOD     
   END TYPE
   ! number of bonds between residues
   INTEGER :: NBINTER = 0 
   ! number of bonds within residues
   INTEGER :: NBINTRA = 0
   ! number of angles spanning multiple residues
   INTEGER :: NAINTER = 0 
   ! number of angles within nucleotide
   INTEGER :: NAINTRA = 0
   ! number of qangles spanning multiple nulceotides
   INTEGER :: NQINTER = 0
   ! number of qangles within nucleotide
   INTEGER :: NQINTRA = 0
   ! number of dihedrals spanning multiple nucleotides
   INTEGER :: NDINTER = 0
   ! number of dihedrals within nucleotide
   INTEGER :: NDINTRA = 0
   ! res type for each of the data types above
   INTEGER, ALLOCATABLE :: BINTERTYPE(:), BINTRATYPE(:), AINTERTYPE(:), AINTRATYPE(:), &
                           QINTERTYPE(:), QINTRATYPE(:), DINTERTYPE(:), DINTRATYPE(:)
   ! number of terms for each dihedral
   INTEGER, ALLOCATABLE :: DINTERTERMS(:), DINTRATERMS(:)
   ! maximum number of terms in dihedrals
   INTEGER, PARAMETER :: MAXNTERM = 3
   !storing bond information
   TYPE(BOND), ALLOCATABLE :: BINTER(:), BINTRA(:)
   !storing angle information
   TYPE(ANGLE), ALLOCATABLE :: AINTER(:), AINTRA(:)
   !storing qangle information
   TYPE(QANGLE), ALLOCATABLE :: QINTER(:), QINTRA(:)
   !storing dihedrals
   TYPE(DIHEDRAL), ALLOCATABLE :: DINTER(:,:), DINTRA(:,:)

   CONTAINS
      SUBROUTINE ALLOCATE_FF_GLOBALS()
         CALL DEALLOC_FF_GLOBALS()
         ALLOCATE(BINTER(NBINTER),BINTERTYPE(NBINTER))
         ALLOCATE(BINTRA(NBINTRA),BINTRATYPE(NBINTRA))
         ALLOCATE(AINTER(NAINTER),AINTERTYPE(NAINTER))
         ALLOCATE(AINTRA(NAINTRA),AINTRATYPE(NAINTRA))
         ALLOCATE(QINTER(NQINTER),QINTERTYPE(NQINTER))
         ALLOCATE(QINTRA(NQINTRA),QINTRATYPE(NQINTRA))
         ALLOCATE(DINTER(NDINTER,MAXNTERM),DINTERTYPE(NDINTER),DINTERTERMS(NDINTER))
         ALLOCATE(DINTRA(NDINTRA,MAXNTERM),DINTRATYPE(NDINTRA),DINTRATERMS(NDINTRA))         
      END SUBROUTINE ALLOCATE_FF_GLOBALS


      SUBROUTINE DEALLOC_FF_GLOBALS()
         IF (ALLOCATED(BINTER)) DEALLOCATE(BINTER)
         IF (ALLOCATED(BINTERTYPE)) DEALLOCATE(BINTERTYPE)
         IF (ALLOCATED(BINTRA)) DEALLOCATE(BINTRA)
         IF (ALLOCATED(BINTRATYPE)) DEALLOCATE(BINTRATYPE)
         IF (ALLOCATED(AINTER)) DEALLOCATE(AINTER)
         IF (ALLOCATED(AINTERTYPE)) DEALLOCATE(AINTERTYPE)
         IF (ALLOCATED(AINTRA)) DEALLOCATE(AINTRA)
         IF (ALLOCATED(AINTRATYPE)) DEALLOCATE(AINTRATYPE)
         IF (ALLOCATED(QINTER)) DEALLOCATE(QINTER)
         IF (ALLOCATED(QINTERTYPE)) DEALLOCATE(QINTERTYPE)
         IF (ALLOCATED(QINTRA)) DEALLOCATE(QINTRA)
         IF (ALLOCATED(QINTRATYPE)) DEALLOCATE(QINTRATYPE)
         IF (ALLOCATED(DINTER)) DEALLOCATE(DINTER)
         IF (ALLOCATED(DINTERTYPE)) DEALLOCATE(DINTERTYPE)
         IF (ALLOCATED(DINTRA)) DEALLOCATE(DINTRA)
         IF (ALLOCATED(DINTRATYPE)) DEALLOCATE(DINTRATYPE)  
         IF (ALLOCATED(DINTERTERMS)) DEALLOCATE(DINTERTERMS)          
         IF (ALLOCATED(DINTRATERMS)) DEALLOCATE(DINTRATERMS)           
      END SUBROUTINE DEALLOC_FF_GLOBALS

END MODULE FF_GLOBALS