MODULE PARSE_FF
   USE PREC_HIRE
   USE FF_GLOBALS

   CONTAINS
      SUBROUTINE PARSE_FF_FILES(NFF,FFFILES)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: NFF
         CHARACTER(LEN=30), INTENT(IN) :: FFFILES(NFF)


      END SUBROUTINE PARSE_FF_FILES

      SUBROUTINE READ_FF_FILE(FNAME)
         USE UTILS_IO, ONLY: FILE_OPEN
         IMPLICIT NONE
         CHARACTER(LEN=30), INTENT(IN) :: FNAME
         INTEGER :: INUNIT
         CHARACTER(LEN=200) :: LINE
         INTEGER :: IOSTAT

         CALL FILE_OPEN(FNAME, INUNIT, .FALSE.)

         IOSTAT=0
         DO WHILE (IOSTAT.EQ.0)
            READ(INUNIT,'(A)',IOSTAT=IOSTAT) LINE
            IF (TRIM(ADJUSTL(LINE)).EQ."#FILECONTENT") THEN
               READ(LINE,*) NBINTER, NBINTRA, NAINTER, NAINTRA, NQINTER, NQINTRA, NDINTER, NDINTRA
            END IF
         END DO
         CLOSE(INUNIT)
      END SUBROUTINE READ_FF_FILE


END MODULE PARSE_FF