SUBROUTINE MD_FINISH
   USE MD_UTILS, ONLY: DEALLOC_COMMONS
   USE HIRE_INTERFACE, ONLY: TERMINATE_HIRE
   USE MD_COMMONS, ONLY: XUNIT, EUNIT, MYUNIT
   WRITE(MYUNIT,*) " md_finish> MD simulation completed"
   CLOSE(XUNIT)
   CLOSE(EUNIT)
   CALL TERMINATE_HIRE()
   CALL DEALLOC_COMMONS()
END SUBROUTINE MD_FINISH