SUBROUTINE MD_FINISH
   USE MD_UTILS, ONLY: DEALLOC_COMMONS, XUNIT, EUNIT, MYUNIT
   WRITE(MYUNIT,*) " md_finish> MD simulation completed"
   CLOSE(XUNIT)
   CLOSE(EUNIT)
   CALL DEALLOC_COMMONS()
END SUBROUTINE MD_FINISH