MODULE MOD_IMD
   USE NUMKIND
   USE MD_COMMONS, ONLY: NOPT, NATOMS
   IMPLICIT NONE
   REAL(KIND=REAL64), ALLOCATABLE :: IMD_FORCES(:)
   LOGICAL :: IMDT = .FALSE.
   CONTAINS 
      SUBROUTINE IMD_SETUP()
         IMPLICIT NONE
         ! allocate the required variables
         CALL ALLOC_IMD()
         ! initialise thoise variables as required
         IMD_FORCES(1:NOPT) = 0.0D0
         IMDT = .TRUE.
         
      END SUBROUTINE IMD_SETUP

      SUBROUTINE ALLOC_IMD()
         CALL DEALLOC_IMD()
         ALLOCATE(IMD_FORCES(NOPT))
      END SUBROUTINE ALLOC_IMD

      SUBROUTINE DEALLOC_IMD()
         IMPLICIT NONE
         IF (ALLOCATED(IMD_FORCES))  DEALLOCATE(IMD_FORCES)
      END SUBROUTINE DEALLOC_IMD

END MODULE MOD_IMD