! Subroutines to handle the exchange of system replicas in PT basin-hopping 

SUBROUTINE BHPT_GET_DESTINATION(NSTEP,DEST)
USE PREC
USE COMMONS, ONLY: PTRANDOM, PTINTERVAL, PTSINGLE, PTSETS, NPAR, MYNODE, EXCHPROB, EXCHINT
IMPLICIT NONE
REAL(KIND = REAL64)  :: DPRAND_UNIVERSAL
INTEGER, INTENT(IN)  :: NSTEP
INTEGER, INTENT(OUT) :: DEST

DEST=-1
IF (PTRANDOM) THEN
   IF (DPRAND_UNIVERSAL().GT.EXCHPROB) THEN
      DEST=-1

   ELSE IF (PTSINGLE) THEN
      DEST=INT(DPRAND_UNIVERSAL()*(NPAR-1))
      IF (MYNODE.EQ.DEST) THEN
         DEST=DEST+1
      ELSE IF (MYNODE.EQ.(DEST+1)) THEN
      ELSE
         DEST=-1
      ENDIF

   ELSE IF (PTSETS) THEN
      DEST=INT(DPRAND_UNIVERSAL()*2.D0)
      IF (MOD(MYNODE+DEST,2)==0) THEN
         DEST=MOD(MYNODE+1,NPAR)
         IF (DEST==0) DEST=-1
      ELSE IF (MOD(MYNODE+DEST,2)==1) THEN
         DEST=MOD(MYNODE-1,NPAR)
         IF (DEST==NPAR-1) DEST=-1
      ENDIF
   ENDIF

ELSE IF (PTINTERVAL) THEN
   IF (MOD(NSTEP,INT(EXCHINT))/=0) THEN
      DEST=-1
   ELSE IF (PTSINGLE) THEN
      DEST=INT(DPRAND_UNIVERSAL()*(NPAR-1))
      IF (MYNODE==DEST) THEN
         DEST=MYNODE+1
      ELSE IF (MYNODE==DEST+1) THEN
      ELSE
         DEST=-1
      ENDIF

   ELSE IF (PTSETS) THEN
      DEST=MOD(INT(NSTEP/EXCHINT+1.D0),2)
      IF (MOD(MYNODE+DEST,2)==0) THEN
         DEST=MOD(MYNODE+1,NPAR)
         IF (DEST==0) DEST=-1
      ELSE IF (MOD(MYNODE+DEST,2)==1) THEN
         DEST=MOD(MYNODE-1,NPAR)
         IF (DEST==NPAR-1) DEST=-1
      ENDIF
   ENDIF
ENDIF

END SUBROUTINE BHPT_GET_DESTINATION

!----------------------------------------------------------------------------------------------------------------------------------!

SUBROUTINE BHPT_EXCHANGE(BETA,NSTEP,NTOT,NEACCEPT)
USE COMMONS
USE PREC
IMPLICIT NONE
REAL(KIND = REAL64)    :: BETA(NPAR)
INTEGER, INTENT(IN)    :: NSTEP
INTEGER, INTENT(INOUT) :: NTOT, NEACCEPT
INTEGER                :: DEST
LOGICAL                :: SUCCESS
#ifdef MPI
INCLUDE 'mpif.h'
REAL(KIND = REAL64)    :: DBETA, DELTA, DPRAND, DPRAND_UNIVERSAL, E
INTEGER                :: I, MPIERR
INTEGER                :: ATTEMPTSTATUS(MPI_STATUS_SIZE), EXCHSTATUS(MPI_STATUS_SIZE,6), REQ(6)

CALL BHPT_GET_DESTINATION(NSTEP,DEST)

IF (DEST==-1) RETURN

NTOT=NTOT+1

IF (MOD(DEST,2)==0) THEN
   CALL MPI_SEND(EPREV(MYNODE+1),1,MPI_DOUBLE_PRECISION,DEST,100,MPI_COMM_WORLD,MPIERR) 
   CALL MPI_RECV(SUCCESS,1,MPI_LOGICAL,DEST,101,MPI_COMM_WORLD,ATTEMPTSTATUS,MPIERR) 
ELSE
   CALL MPI_RECV(E,1,MPI_DOUBLE_PRECISION,DEST,100,MPI_COMM_WORLD,ATTEMPTSTATUS,MPIERR) 
   DELTA=EPREV(MYNODE+1)-E
   DBETA=BETA(MYNODE+1)-BETA(DEST+1)
   SUCCESS=DEXP(DELTA*DBETA)>=DPRAND()
   CALL MPI_SEND(SUCCESS,1,MPI_LOGICAL,DEST,101,MPI_COMM_WORLD,MPIERR) 
ENDIF

IF (SUCCESS) THEN
   E=EPREV(MYNODE+1)
   COORDSO(1:3*NATOMS,MYNODE+1)=COORDS(1:3*NATOMS,MYNODE+1)
   CALL MPI_IRECV(EPREV(MYNODE+1),1,MPI_DOUBLE_PRECISION,DEST,102,MPI_COMM_WORLD,REQ(3),MPIERR) 
   CALL MPI_IRECV(COORDS(1:3*NATOMS,MYNODE+1),3*NATOMS,MPI_DOUBLE_PRECISION,DEST,103,MPI_COMM_WORLD,REQ(4),MPIERR) 
   CALL MPI_ISEND(E,1,MPI_DOUBLE_PRECISION,DEST,102,MPI_COMM_WORLD,REQ(1),MPIERR) 
   CALL MPI_ISEND(COORDSO(1:3*NATOMS,MYNODE+1),3*NATOMS,MPI_DOUBLE_PRECISION,DEST,103,MPI_COMM_WORLD,REQ(2),MPIERR) 
   DO I=1,4
      CALL MPI_WAIT(REQ(I),EXCHSTATUS(1,I),MPIERR) 
   ENDDO
   IF (TBP) THEN 
      TBPBASINSO(:)=TBPBASINS(:)
      CALL MPI_IRECV(TBPBASINS,TBPSTEPS,MPI_INTEGER,DEST,104,MPI_COMM_WORLD,REQ(6),MPIERR)
      CALL MPI_ISEND(TBPBASINSO,TBPSTEPS,MPI_INTEGER,DEST,104,MPI_COMM_WORLD,REQ(5),MPIERR)
      DO I=5,6
         CALL MPI_WAIT(REQ(I),EXCHSTATUS(1,I),MPIERR) 
      ENDDO
   ENDIF
   WRITE(MYUNIT,'(A,I0.2,A,I0.2,A)')"[",MYNODE+1,"]BHPT>Exchange with [",DEST+1,"] successful."
ELSE
   WRITE(MYUNIT,'(A,I0.2,A,I0.2,A)')"[",MYNODE+1,"]BHPT>Exchange with [",DEST+1,"] rejected."
ENDIF

IF (SUCCESS) NEACCEPT=NEACCEPT+1

#else
#endif
END SUBROUTINE BHPT_EXCHANGE

!----------------------------------------------------------------------------------------------------------------------------------!

SUBROUTINE BHPT_IO(TIME,NQTOT,NPCALL1,NTOT,NEACCEPT)
USE PREC
#ifdef MPI
USE COMMONS, ONLY: MYNODE, MYUNIT
#endif
IMPLICIT NONE
REAL(KIND = REAL64)   :: TIME
INTEGER               :: NQTOT, NPCALL1, NTOT, NEACCEPT
#ifdef MPI
INCLUDE 'mpif.h'
REAL(KIND = REAL64)   :: SENDARR(5), RECVARR(5)
INTEGER               :: MPIERR

!jdf43>  collates the statistics of all runs, and prints both local and global
!        stats.

SENDARR(1)=TIME
SENDARR(2)=NQTOT
SENDARR(3)=NPCALL1
SENDARR(4)=NTOT
SENDARR(5)=NEACCEPT

WRITE(MYUNIT,'(A,I0.2,A,2(I5,A))')'[',MYNODE+1,']BHPT_IO>',NEACCEPT,' out of ',NTOT,' exchanges accepted in this process.'
WRITE(MYUNIT,'(A,I0.2,A,2(I20),F20.2)')'[',MYNODE+1,']BHPT_IO>Local quenches / function calls / time:',NQTOT,NPCALL1,TIME

CALL MPI_BARRIER(MPI_COMM_WORLD,MPIERR)
CALL MPI_ALLREDUCE(SENDARR,RECVARR,5,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,MPIERR)

TIME=RECVARR(1)
NQTOT=RECVARR(2)
NPCALL1=RECVARR(3)
NTOT=RECVARR(4)/2
NEACCEPT=RECVARR(5)/2

WRITE(MYUNIT,'(2(A,I5),A)')'[--]BHPT_IO>',NEACCEPT,' out of ',NTOT,' exchanges accepted overall.'
WRITE(MYUNIT,'(A,2(I20),F20.2)')'[--]BHPT_IO>Total quenches / function calls / time:',NQTOT,NPCALL1,TIME

#else
#endif
END SUBROUTINE BHPT_IO

!----------------------------------------------------------------------------------------------------------------------------------!
