! Subroutine to count the number of atoms, needed to allocate memory correctly

MODULE NOA
  USE HIRE_INTERFACE, ONLY: HIRE_INITIALISE
  USE COMMONS, ONLY: MYUNIT, SCALENAME, TOPNAME
  IMPLICIT NONE
  SAVE
  INTEGER :: NUMBER_OF_ATOMS
  
CONTAINS
  
  SUBROUTINE COUNTATOMS()    
    IMPLICIT NONE
    LOGICAL :: YESNO,YESNOSC
    
    INQUIRE(FILE=TOPNAME,EXIST=YESNO)
    INQUIRE(FILE=SCALENAME,EXIST=YESNOSC)    
    NUMBER_OF_ATOMS=0
    IF (YESNO.AND.YESNOSC) THEN
        CALL HIRE_INITIALISE(TOPNAME,SCALENAME,NUMBER_OF_ATOMS)
    ELSE
        WRITE(MYUNIT , '(A)') 'countatoms> Cannot locate input files'
        STOP 
    ENDIF

    RETURN
  END SUBROUTINE COUNTATOMS

END MODULE NOA
