!  Energy and gradient for harmonic field

   SUBROUTINE HARMONICFIELD(X,X0,V,E)
      USE COMMONS, ONLY : HARMONICSTR
      USE PREC
      IMPLICIT NONE
      REAL(KIND = REAL64), INTENT(IN) :: X(3), X0(3)
      REAL(KIND = REAL64), INTENT(OUT) :: V(3), E
      REAL(KIND = REAL64) :: DX,DY,DZ,DR

      DX = X(1)-X0(1) 
      DY = X(2)-X0(2) 
      DZ = X(3)-X0(3) 
      DR = SQRT(DX**2 + DY**2 + DZ**2)

      E = E + HARMONICSTR*DR**2

      V(1) = V(1) + HARMONICSTR*2.0D0*DX
      V(2) = V(2) + HARMONICSTR*2.0D0*DY
      V(3) = V(3) + HARMONICSTR*2.0D0*DZ

   END SUBROUTINE HARMONICFIELD


   SUBROUTINE HARMOVECONSTR(X, I, J, GRAD, EREAL)
      USE COMMONS, ONLY: NATOMS, BPDIST, BPSTRENGTH
      USE PREC
      REAL(KIND = REAL64), INTENT(IN) :: X(3*NATOMS)
      REAL(KIND = REAL64), INTENT(INOUT) :: GRAD(3*NATOMS), EREAL
      INTEGER, INTENT(IN) :: I, J
      REAL(KIND = REAL64) :: RIJ, DA, DF, XA, YA, ZA, XIJ, YIJ, ZIJ

      XIJ = X(3*I-2) - X(3*J-2)
      YIJ = X(3*I-1) - X(3*J-1)
      ZIJ = X(3*I) - X(3*J)
      RIJ = SQRT(XIJ*XIJ + YIJ*YIJ + ZIJ*ZIJ)
      DA = RIJ - BPDIST
      EREAL = EREAL + BPSTRENGTH*DA*DA
      DF = 2*BPSTRENGTH*DA/RIJ
      XA = DF*XIJ
      YA = DF*YIJ
      ZA = DF*ZIJ
      GRAD(3*I-2) = GRAD(3*I-2) + XA
      GRAD(3*J-2) = GRAD(3*J-2) - XA
      GRAD(3*I-1) = GRAD(3*I-1) + YA
      GRAD(3*J-1) = GRAD(3*J-1) - YA
      GRAD(3*I) = GRAD(3*I) + ZA
      GRAD(3*J) = GRAD(3*J) - ZA
      RETURN
   END SUBROUTINE HARMOVECONSTR
