
SUBROUTINE MCRUNS
   USE COMMONS, ONLY: NATOMS, CHECKDT, COORDS, &
                      MCSTEPS, TFAC, RELAXFQ, NSAVE, QMINP
   USE GENRIGID, ONLY: RIGIDINIT
   USE MCmod, ONLY: MC
   USE PREC, ONLY: REAL64

   IMPLICIT NONE
   LOGICAL                    :: LOPEN
   REAL(REAL64), ALLOCATABLE  :: QMINPTMP(:, :)
   INTEGER :: GETUNIT, DUMPPUNIT

   INQUIRE(UNIT=1, OPENED=LOPEN)
   IF (LOPEN) THEN
      WRITE(*,'(A,I2,A)') 'mcruns> ERROR *** Unit ', 1, ' is not free '
      STOP
   ENDIF

! If checking derivatives, call CHECKD, which then exits
   IF (CHECKDT) THEN
      CALL CHECKD(COORDS(:, :))
   END IF

   CALL MC(MCSTEPS,TFAC)

   IF (RELAXFQ) THEN
      ALLOCATE(QMINPTMP(NSAVE, 3*NATOMS))
      QMINPTMP(:,:) = QMINP(:,:)
      RELAXFQ = .FALSE.
      RIGIDINIT = .TRUE.
      CALL FINALQ()
      CALL FINALIO()
      QMINP(:,:) = QMINPTMP(:,:)
      DEALLOCATE(QMINPTMP)
      RELAXFQ = .TRUE.
      RIGIDINIT = .FALSE.
   END IF
   CALL FINALQ()
   CALL FINALIO()
   IF (DUMPPIGST) THEN
      DUMPPUNIT = GETUNIT()
      OPEN(UNIT=DUMPPUNIT, FILE="E_PiGS.out", STATUS='NEW')
      WRITE(DUMPPUNIT, '(2F15.7)') EPIGSSAVE
      CLOSE(DUMPPUNIT)
   ENDIF
   RETURN

END SUBROUTINE MCRUNS
