SUBROUTINE POTENTIAL(X, GRAD, EREAL, GRADT, SECT)
   USE COMMONS
   USE GENRIGID, ONLY: RIGIDINIT, NRIGIDBODY, DEGFREEDOMS, ATOMRIGIDCOORDT, &
                       AACONVERGENCET, AACONVERGENCE, TRANSFORMRIGIDTOC, &
                       TRANSFORMGRAD, TRANSFORMHESSIAN
   USE PREC
   USE PORFUNCS
   USE MODHESS, ONLY: HESS, RBAANORMALMODET
   USE HIRE_INTERFACE, ONLY: HIRE_ENERGY_GRAD, HIRE_NUMHESS
   USE DEFS_MCRUNS
   USE TWIST_MOD, ONLY: TWISTT, TWIST
   
   IMPLICIT NONE
   ! Arguments
   REAL(KIND = REAL64), INTENT(INOUT)  :: X(3*NATOMS)
   REAL(KIND = REAL64), INTENT(OUT)    :: GRAD(3*NATOMS)
   REAL(KIND = REAL64), INTENT(OUT)    :: EREAL
   LOGICAL, INTENT(IN)                 :: GRADT
   LOGICAL, INTENT(IN)                 :: SECT

   ! Variables
   INTEGER :: J1, I, J
   REAL(KIND = REAL64) :: DUMMY2
   REAL(KIND = REAL64) :: XCOORDS(3*NATOMS), GRADATOMS(3*NATOMS)
   REAL(KIND = REAL64) :: XRIGIDCOORDS(3*NATOMS), XRIGIDGRAD(3*NATOMS) 
   REAL(KIND = REAL64) :: XRIGIDHESS(DEGFREEDOMS, DEGFREEDOMS)

   ! Count the number of potential calls.
   NPCALL=NPCALL+1
10 CONTINUE

   ! If coordinates are atomistic (i.e. no rigid bodies) just call the energy
   ! and gradient
   IF (ATOMRIGIDCOORDT) THEN
      CALL HIRE_ENERGY_GRAD(3*NATOMS, X, EREAL, GRADATOMS)
      GRAD(1:3*NATOMS)=GRADATOMS(:) 
   ! If the coordinates include rigid bodies, transform them back to being
   ! atomistic first
   ELSE
      XRIGIDCOORDS(1:DEGFREEDOMS)=X(1:DEGFREEDOMS)
      CALL TRANSFORMRIGIDTOC(1, NRIGIDBODY, XCOORDS, XRIGIDCOORDS)
      CALL HIRE_ENERGY_GRAD(3*NATOMS, X, EREAL, GRADATOMS)
      GRAD(1:3*NATOMS)=GRADATOMS(:)
      !Transform the gradient and coordinates back to the rigid body representation
      CALL TRANSFORMGRAD(GRADATOMS, XRIGIDCOORDS, XRIGIDGRAD)
      X(1:DEGFREEDOMS)=XRIGIDCOORDS(1:DEGFREEDOMS)
      X(DEGFREEDOMS+1:3*NATOMS)=0.0D0
      GRAD(1:DEGFREEDOMS)=XRIGIDGRAD(1:DEGFREEDOMS)
      GRAD(DEGFREEDOMS+1:3*NATOMS)=0.0D0
   END IF
   !copied from OPTIM, rbody part not tested
   IF (SECT) THEN
      IF (ALLOCATED(HESS)) DEALLOCATE(HESS)
      ALLOCATE(HESS(3*NATOMS, 3*NATOMS))
      CALL HIRE_NUMHESS(3*NATOMS,X, DELTA=1.0D-5, HESSIAN=HESS(:, :))
      IF (RIGIDINIT .AND. (.NOT. ATOMRIGIDCOORDT) ) THEN
         CALL TRANSFORMHESSIAN(HESS, GRADATOMS, XRIGIDCOORDS,XRIGIDHESS,RBAANORMALMODET)
         HESS(DEGFREEDOMS+1:3*NATOMS,:) = 0.0D0
         HESS(:,DEGFREEDOMS+1:3*NATOMS) = 0.0D0
         HESS(1:DEGFREEDOMS,1:DEGFREEDOMS) =XRIGIDHESS(1:DEGFREEDOMS,1:DEGFREEDOMS)
      END IF
   END IF

!
!  --------------- End of possible potentials - now add fields if required ------------------------------
!

   IF (PULLT) THEN
      EREAL=EREAL - PFORCE*(X(3*(PATOM1-1)+3)-X(3*(PATOM2-1)+3))
      GRAD(3*(PATOM1-1)+3)=GRAD(3*(PATOM1-1)+3) - PFORCE
      GRAD(3*(PATOM2-1)+3)=GRAD(3*(PATOM2-1)+3) + PFORCE
   END IF


! Apply twist forces, if appropriate
   IF (TWISTT) THEN
      CALL TWIST(X(1:3*NATOMS), NATOMS, GRAD(1:3*NATOMS), EREAL)
   END IF

! apply harmonic field for keyword HARMONICF
   IF ( HARMONICF ) THEN
      DO J1=1, NATOMS
         IF (HARMONICFLIST(J1)) THEN
            CALL HARMONICFIELD( X(3*J1-2), HARMONICR0(3*J1-2), GRAD(3*J1-2), EREAL)
         END IF
      END DO
   END IF

! apply harmonic field for global moves
   IF ( HARMONICPOT ) THEN
      I = HARMATOMS(1)
      J = HARMATOMS(2)
      CALL HARMOVECONSTR(X, I, J, GRAD, EREAL)
   END IF   


   IF (GRADT) THEN
      IF (FREEZE) THEN
         DO J1=1, NATOMS
            IF (FROZEN(J1)) GRAD(3*J1-2 : 3*J1)=0.0D0             
         END DO
      END IF

      IF (RIGIDINIT .AND. (.NOT. ATOMRIGIDCOORDT)) THEN
         DUMMY2=SUM(GRAD(1:DEGFREEDOMS)**2)
         RMS=MAX(SQRT(DUMMY2/DEGFREEDOMS), 1.0D-100)
         IF ((RMS < 5.0D0 * BQMAX) .AND. AACONVERGENCET) THEN
            CALL AACONVERGENCE(GRADATOMS, XRIGIDCOORDS, XRIGIDGRAD, RMS)
         END IF
      ELSE
         DUMMY2=SUM(GRAD(1:2*NATOMS)**2)
         RMS=MAX(DSQRT(DUMMY2/(2*NATOMS)), 1.0D-100)
      END IF
      IF(DEBUG.AND.(RMS.NE.RMS)) THEN
         WRITE(MYUNIT,'(A)' ) 'potential> WARNING - RMS force is NaN'
      END IF
   END IF

END SUBROUTINE POTENTIAL
